name: Discord Notification on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]  # 當 Pull Request 被創建、更新或重新開啟時觸發

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send message to Discord
      uses: fjogeleit/http-request-action@v1.2.0  # 使用支持 Webhook 的 Action
      with:
        url: ${{ secrets.DISCORD_WEBHOOK_URL }}  # 使用 GitHub Secrets 存儲 Webhook URL
        method: POST
        headers: '{"Content-Type": "application/json"}'
        body: '{"content": "A new pull request has been created or updated: ${{ github.event.pull_request.html_url }}"}'
